// Generated by npm run assets:generate. Edit scripts/scene-art.mjs.
export const sceneAssets = {
  "reference-plant-room": {
    "indoor": true,
    "regions": [
      {
        "id": "wall",
        "label": "벽과 창가",
        "material": "stone"
      },
      {
        "id": "floor",
        "label": "바닥",
        "material": "wood"
      },
      {
        "id": "plants",
        "label": "화분과 잎",
        "material": "foliage"
      },
      {
        "id": "chairs",
        "label": "천 의자",
        "material": "fabric"
      },
      {
        "id": "table",
        "label": "작은 테이블",
        "material": "wood"
      }
    ]
  },
  "window-still-life": {
    "indoor": true,
    "regions": [
      {
        "id": "wall",
        "label": "벽과 창문",
        "material": "stone"
      },
      {
        "id": "table",
        "label": "나무 테이블",
        "material": "wood"
      },
      {
        "id": "cloth",
        "label": "접힌 천",
        "material": "fabric"
      },
      {
        "id": "cup",
        "label": "컵과 접시",
        "material": "ceramic"
      },
      {
        "id": "plants",
        "label": "창가 화분",
        "material": "foliage"
      }
    ]
  },
  "lakeside": {
    "indoor": false,
    "regions": [
      {
        "id": "sky",
        "label": "하늘",
        "material": "other"
      },
      {
        "id": "mountains",
        "label": "먼 산",
        "material": "stone"
      },
      {
        "id": "water",
        "label": "호수의 수면",
        "material": "water"
      },
      {
        "id": "shore",
        "label": "앞쪽 물가",
        "material": "stone"
      },
      {
        "id": "tree",
        "label": "물가의 나무",
        "material": "foliage"
      }
    ]
  }
} as const
