// Generated by npm run assets:generate. Edit scripts/scenes/<id>.mjs.
export const sceneAssets = {
  "reference-plant-room": {
    "indoor": true,
    "regions": [
      {
        "id": "wall",
        "label": "벽과 창",
        "material": "stone"
      },
      {
        "id": "floor",
        "label": "바닥",
        "material": "wood"
      },
      {
        "id": "shelf",
        "label": "식물 선반",
        "material": "wood"
      },
      {
        "id": "plants",
        "label": "화분과 잎",
        "material": "foliage"
      },
      {
        "id": "table",
        "label": "작은 테이블",
        "material": "wood"
      },
      {
        "id": "teaset",
        "label": "찻주전자와 컵",
        "material": "ceramic"
      },
      {
        "id": "chairs",
        "label": "접이식 의자",
        "material": "fabric"
      }
    ]
  },
  "window-still-life": {
    "indoor": true,
    "regions": [
      {
        "id": "wall",
        "label": "벽과 창문",
        "material": "stone"
      },
      {
        "id": "curtain",
        "label": "커튼",
        "material": "fabric"
      },
      {
        "id": "table",
        "label": "나무 테이블",
        "material": "wood"
      },
      {
        "id": "cloth",
        "label": "접힌 천",
        "material": "fabric"
      },
      {
        "id": "books",
        "label": "책",
        "material": "other"
      },
      {
        "id": "teapot",
        "label": "찻주전자",
        "material": "ceramic"
      },
      {
        "id": "cup",
        "label": "컵과 접시",
        "material": "ceramic"
      },
      {
        "id": "fruit",
        "label": "과일과 그릇",
        "material": "other"
      },
      {
        "id": "plants",
        "label": "창가 화분",
        "material": "foliage"
      },
      {
        "id": "vase",
        "label": "유리 화병",
        "material": "other"
      }
    ]
  },
  "lakeside": {
    "indoor": false,
    "regions": [
      {
        "id": "sky",
        "label": "하늘",
        "material": "other"
      },
      {
        "id": "mountains",
        "label": "먼 산",
        "material": "stone"
      },
      {
        "id": "water",
        "label": "호수의 수면",
        "material": "water"
      },
      {
        "id": "dock",
        "label": "나무 선착장",
        "material": "wood"
      },
      {
        "id": "boat",
        "label": "작은 배",
        "material": "wood"
      },
      {
        "id": "shore",
        "label": "앞쪽 물가",
        "material": "stone"
      },
      {
        "id": "tree",
        "label": "물가의 나무",
        "material": "foliage"
      }
    ]
  },
  "cafe-corner": {
    "indoor": true,
    "regions": [
      {
        "id": "wall",
        "label": "카페 벽과 창문",
        "material": "stone"
      },
      {
        "id": "floor",
        "label": "카페 바닥",
        "material": "wood"
      },
      {
        "id": "shelf",
        "label": "벽 선반",
        "material": "wood"
      },
      {
        "id": "lamp",
        "label": "펜던트 조명",
        "material": "other"
      },
      {
        "id": "plants",
        "label": "창가의 초록",
        "material": "foliage"
      },
      {
        "id": "chairs",
        "label": "카페 의자",
        "material": "fabric"
      },
      {
        "id": "table",
        "label": "원형 테이블",
        "material": "wood"
      },
      {
        "id": "tableware",
        "label": "컵과 접시",
        "material": "ceramic"
      }
    ]
  },
  "garden-path": {
    "indoor": false,
    "regions": [
      {
        "id": "sky",
        "label": "나무 사이 하늘",
        "material": "other"
      },
      {
        "id": "grass",
        "label": "풀과 작은 잎",
        "material": "foliage"
      },
      {
        "id": "path",
        "label": "정원의 길",
        "material": "stone"
      },
      {
        "id": "trees",
        "label": "큰 나무와 가지",
        "material": "foliage"
      },
      {
        "id": "fence",
        "label": "울타리",
        "material": "wood"
      },
      {
        "id": "flowers",
        "label": "꽃",
        "material": "foliage"
      },
      {
        "id": "bench",
        "label": "길 옆 벤치",
        "material": "wood"
      }
    ]
  },
  "old-town-street": {
    "indoor": false,
    "regions": [
      {
        "id": "sky",
        "label": "골목 위 하늘",
        "material": "other"
      },
      {
        "id": "far-facade",
        "label": "골목 끝 건물",
        "material": "stone"
      },
      {
        "id": "left-buildings",
        "label": "왼쪽 건물",
        "material": "stone"
      },
      {
        "id": "right-buildings",
        "label": "오른쪽 건물",
        "material": "stone"
      },
      {
        "id": "road",
        "label": "골목길",
        "material": "stone"
      },
      {
        "id": "flags",
        "label": "만국기",
        "material": "fabric"
      },
      {
        "id": "crates",
        "label": "나무 상자",
        "material": "wood"
      },
      {
        "id": "cafe-set",
        "label": "카페 테이블과 의자",
        "material": "wood"
      },
      {
        "id": "plants",
        "label": "골목의 화분",
        "material": "foliage"
      },
      {
        "id": "bicycle",
        "label": "자전거",
        "material": "other"
      }
    ]
  }
} as const
export const sceneAssetVersion = '41d82956e3ffa22b'
export const scenePackFiles = {
  "reference-plant-room": [
    "assets/scenes/reference-plant-room/line-art.svg",
    "assets/scenes/reference-plant-room/base-wash.svg",
    "assets/scenes/reference-plant-room/thumbnail.svg",
    "assets/scenes/reference-plant-room/masks/wall.svg",
    "assets/scenes/reference-plant-room/masks/floor.svg",
    "assets/scenes/reference-plant-room/masks/shelf.svg",
    "assets/scenes/reference-plant-room/masks/plants.svg",
    "assets/scenes/reference-plant-room/masks/table.svg",
    "assets/scenes/reference-plant-room/masks/teaset.svg",
    "assets/scenes/reference-plant-room/masks/chairs.svg",
    "assets/scenes/reference-plant-room/guides/leaves.svg",
    "assets/scenes/reference-plant-room/guides/pots.svg",
    "assets/scenes/reference-plant-room/guides/cushion.svg",
    "assets/scenes/reference-plant-room/guides/chair-frame.svg",
    "assets/scenes/reference-plant-room/guides/upper-left-shadow.svg",
    "assets/scenes/reference-plant-room/guides/upper-left-long-shadow.svg",
    "assets/scenes/reference-plant-room/guides/upper-left-highlight.svg",
    "assets/scenes/reference-plant-room/guides/upper-right-shadow.svg",
    "assets/scenes/reference-plant-room/guides/upper-right-long-shadow.svg",
    "assets/scenes/reference-plant-room/guides/upper-right-highlight.svg",
    "assets/scenes/reference-plant-room/guides/left-shadow.svg",
    "assets/scenes/reference-plant-room/guides/left-long-shadow.svg",
    "assets/scenes/reference-plant-room/guides/left-highlight.svg",
    "assets/scenes/reference-plant-room/guides/right-shadow.svg",
    "assets/scenes/reference-plant-room/guides/right-long-shadow.svg",
    "assets/scenes/reference-plant-room/guides/right-highlight.svg"
  ],
  "window-still-life": [
    "assets/scenes/window-still-life/line-art.svg",
    "assets/scenes/window-still-life/base-wash.svg",
    "assets/scenes/window-still-life/thumbnail.svg",
    "assets/scenes/window-still-life/masks/wall.svg",
    "assets/scenes/window-still-life/masks/curtain.svg",
    "assets/scenes/window-still-life/masks/table.svg",
    "assets/scenes/window-still-life/masks/cloth.svg",
    "assets/scenes/window-still-life/masks/books.svg",
    "assets/scenes/window-still-life/masks/teapot.svg",
    "assets/scenes/window-still-life/masks/cup.svg",
    "assets/scenes/window-still-life/masks/fruit.svg",
    "assets/scenes/window-still-life/masks/plants.svg",
    "assets/scenes/window-still-life/masks/vase.svg",
    "assets/scenes/window-still-life/guides/upper-left-shadow.svg",
    "assets/scenes/window-still-life/guides/upper-left-long-shadow.svg",
    "assets/scenes/window-still-life/guides/upper-left-highlight.svg",
    "assets/scenes/window-still-life/guides/upper-right-shadow.svg",
    "assets/scenes/window-still-life/guides/upper-right-long-shadow.svg",
    "assets/scenes/window-still-life/guides/upper-right-highlight.svg",
    "assets/scenes/window-still-life/guides/left-shadow.svg",
    "assets/scenes/window-still-life/guides/left-long-shadow.svg",
    "assets/scenes/window-still-life/guides/left-highlight.svg",
    "assets/scenes/window-still-life/guides/right-shadow.svg",
    "assets/scenes/window-still-life/guides/right-long-shadow.svg",
    "assets/scenes/window-still-life/guides/right-highlight.svg"
  ],
  "lakeside": [
    "assets/scenes/lakeside/line-art.svg",
    "assets/scenes/lakeside/base-wash.svg",
    "assets/scenes/lakeside/thumbnail.svg",
    "assets/scenes/lakeside/masks/sky.svg",
    "assets/scenes/lakeside/masks/mountains.svg",
    "assets/scenes/lakeside/masks/water.svg",
    "assets/scenes/lakeside/masks/dock.svg",
    "assets/scenes/lakeside/masks/boat.svg",
    "assets/scenes/lakeside/masks/shore.svg",
    "assets/scenes/lakeside/masks/tree.svg",
    "assets/scenes/lakeside/guides/upper-left-shadow.svg",
    "assets/scenes/lakeside/guides/upper-left-long-shadow.svg",
    "assets/scenes/lakeside/guides/upper-left-highlight.svg",
    "assets/scenes/lakeside/guides/upper-right-shadow.svg",
    "assets/scenes/lakeside/guides/upper-right-long-shadow.svg",
    "assets/scenes/lakeside/guides/upper-right-highlight.svg",
    "assets/scenes/lakeside/guides/left-shadow.svg",
    "assets/scenes/lakeside/guides/left-long-shadow.svg",
    "assets/scenes/lakeside/guides/left-highlight.svg",
    "assets/scenes/lakeside/guides/right-shadow.svg",
    "assets/scenes/lakeside/guides/right-long-shadow.svg",
    "assets/scenes/lakeside/guides/right-highlight.svg"
  ],
  "cafe-corner": [
    "assets/scenes/cafe-corner/line-art.svg",
    "assets/scenes/cafe-corner/base-wash.svg",
    "assets/scenes/cafe-corner/thumbnail.svg",
    "assets/scenes/cafe-corner/masks/wall.svg",
    "assets/scenes/cafe-corner/masks/floor.svg",
    "assets/scenes/cafe-corner/masks/shelf.svg",
    "assets/scenes/cafe-corner/masks/lamp.svg",
    "assets/scenes/cafe-corner/masks/plants.svg",
    "assets/scenes/cafe-corner/masks/chairs.svg",
    "assets/scenes/cafe-corner/masks/table.svg",
    "assets/scenes/cafe-corner/masks/tableware.svg",
    "assets/scenes/cafe-corner/guides/upper-left-shadow.svg",
    "assets/scenes/cafe-corner/guides/upper-left-long-shadow.svg",
    "assets/scenes/cafe-corner/guides/upper-left-highlight.svg",
    "assets/scenes/cafe-corner/guides/upper-right-shadow.svg",
    "assets/scenes/cafe-corner/guides/upper-right-long-shadow.svg",
    "assets/scenes/cafe-corner/guides/upper-right-highlight.svg",
    "assets/scenes/cafe-corner/guides/left-shadow.svg",
    "assets/scenes/cafe-corner/guides/left-long-shadow.svg",
    "assets/scenes/cafe-corner/guides/left-highlight.svg",
    "assets/scenes/cafe-corner/guides/right-shadow.svg",
    "assets/scenes/cafe-corner/guides/right-long-shadow.svg",
    "assets/scenes/cafe-corner/guides/right-highlight.svg"
  ],
  "garden-path": [
    "assets/scenes/garden-path/line-art.svg",
    "assets/scenes/garden-path/base-wash.svg",
    "assets/scenes/garden-path/thumbnail.svg",
    "assets/scenes/garden-path/masks/sky.svg",
    "assets/scenes/garden-path/masks/grass.svg",
    "assets/scenes/garden-path/masks/path.svg",
    "assets/scenes/garden-path/masks/trees.svg",
    "assets/scenes/garden-path/masks/fence.svg",
    "assets/scenes/garden-path/masks/flowers.svg",
    "assets/scenes/garden-path/masks/bench.svg",
    "assets/scenes/garden-path/guides/upper-left-shadow.svg",
    "assets/scenes/garden-path/guides/upper-left-long-shadow.svg",
    "assets/scenes/garden-path/guides/upper-left-highlight.svg",
    "assets/scenes/garden-path/guides/upper-right-shadow.svg",
    "assets/scenes/garden-path/guides/upper-right-long-shadow.svg",
    "assets/scenes/garden-path/guides/upper-right-highlight.svg",
    "assets/scenes/garden-path/guides/left-shadow.svg",
    "assets/scenes/garden-path/guides/left-long-shadow.svg",
    "assets/scenes/garden-path/guides/left-highlight.svg",
    "assets/scenes/garden-path/guides/right-shadow.svg",
    "assets/scenes/garden-path/guides/right-long-shadow.svg",
    "assets/scenes/garden-path/guides/right-highlight.svg"
  ],
  "old-town-street": [
    "assets/scenes/old-town-street/line-art.svg",
    "assets/scenes/old-town-street/base-wash.svg",
    "assets/scenes/old-town-street/thumbnail.svg",
    "assets/scenes/old-town-street/masks/sky.svg",
    "assets/scenes/old-town-street/masks/far-facade.svg",
    "assets/scenes/old-town-street/masks/left-buildings.svg",
    "assets/scenes/old-town-street/masks/right-buildings.svg",
    "assets/scenes/old-town-street/masks/road.svg",
    "assets/scenes/old-town-street/masks/flags.svg",
    "assets/scenes/old-town-street/masks/crates.svg",
    "assets/scenes/old-town-street/masks/cafe-set.svg",
    "assets/scenes/old-town-street/masks/plants.svg",
    "assets/scenes/old-town-street/masks/bicycle.svg",
    "assets/scenes/old-town-street/guides/upper-left-shadow.svg",
    "assets/scenes/old-town-street/guides/upper-left-long-shadow.svg",
    "assets/scenes/old-town-street/guides/upper-left-highlight.svg",
    "assets/scenes/old-town-street/guides/upper-right-shadow.svg",
    "assets/scenes/old-town-street/guides/upper-right-long-shadow.svg",
    "assets/scenes/old-town-street/guides/upper-right-highlight.svg",
    "assets/scenes/old-town-street/guides/left-shadow.svg",
    "assets/scenes/old-town-street/guides/left-long-shadow.svg",
    "assets/scenes/old-town-street/guides/left-highlight.svg",
    "assets/scenes/old-town-street/guides/right-shadow.svg",
    "assets/scenes/old-town-street/guides/right-long-shadow.svg",
    "assets/scenes/old-town-street/guides/right-highlight.svg"
  ]
} as const
