import { mkdir, writeFile } from 'node:fs/promises'
import { artworks } from './scene-art.mjs'

const svg = (content, attrs = '') => `<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="760" viewBox="0 0 1000 760" ${attrs}>${content}</svg>\n`
const generated = {}
for (const art of artworks) {
  const root = `public/assets/scenes/${art.id}`
  await mkdir(`${root}/masks`, { recursive: true })
  await mkdir(`${root}/guides`, { recursive: true })
  const outlines = art.regions.map(r => r.shape).join('') + art.details
  const line = `<g fill="none" stroke="#526253" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">${outlines}</g>`
  const wash = `<rect x="55" y="55" width="890" height="650" rx="3" fill="${art.wash}" opacity=".28"/>` + art.regions.map(r => `<g fill="${r.wash}" opacity=".29" stroke="none">${r.shape}</g>`).join('')
  await writeFile(`${root}/line-art.svg`, svg(line))
  await writeFile(`${root}/base-wash.svg`, svg(wash))
  await writeFile(`${root}/thumbnail.svg`, svg(`<rect width="1000" height="760" fill="#fcfaf3"/>${wash}${line}`))
  for (const r of art.regions) await writeFile(`${root}/masks/${r.id}.svg`, svg(`<g fill="white" stroke="white" stroke-width="2">${r.shape}</g>`))
  for (const [direction, shape] of Object.entries(art.shadows)) {
    const shadedSide = direction.includes('left') || direction === 'left' ? art.facets.left : art.facets.right
    const litSide = direction.includes('left') || direction === 'left' ? art.facets.right : art.facets.left
    await writeFile(`${root}/guides/${direction}-shadow.svg`, svg(`<g fill="white">${shape}${shadedSide}</g>`))
    await writeFile(`${root}/guides/${direction}-highlight.svg`, svg(`<g fill="white">${litSide}</g>`))
  }
  generated[art.id] = { indoor: art.indoor, regions: art.regions.map(({ id, label, material }) => ({ id, label, material })) }
}
await writeFile('src/content/scenes.generated.ts', `// Generated by npm run assets:generate. Edit scripts/scene-art.mjs.\nexport const sceneAssets = ${JSON.stringify(generated, null, 2)} as const\n`)
console.log(`Generated ${artworks.length} aligned SVG scene packs`)
