import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { artworks } from './scene-art.mjs'
import { DIRECTIONS, sceneDocuments } from './scene-svg.mjs'

const generated = {}
const packs = {}
for (const art of artworks) {
  const root = `public/assets/scenes/${art.id}`
  await mkdir(`${root}/masks`, { recursive: true })
  await mkdir(`${root}/guides`, { recursive: true })
  const files = sceneDocuments(art)
  for (const [name, content] of Object.entries(files)) await writeFile(`${root}/${name}`, content)
  generated[art.id] = { indoor: art.indoor, regions: art.regions.map(({ id, label, material }) => ({ id, label, material })) }
  packs[art.id] = ['line-art.svg', 'base-wash.svg', 'thumbnail.svg', ...art.regions.map(region => `masks/${region.id}.svg`), ...DIRECTIONS.flatMap(direction => [`guides/${direction}-shadow.svg`, `guides/${direction}-long-shadow.svg`, `guides/${direction}-highlight.svg`])].map(file => `assets/scenes/${art.id}/${file}`)
}
const hash = createHash('sha256')
for (const file of Object.values(packs).flat().sort()) { hash.update(file); hash.update(await readFile(`public/${file}`)) }
const version = hash.digest('hex').slice(0, 16)
await writeFile('public/scene-packs.json', JSON.stringify({ version, scenes: packs }, null, 2) + '\n')
await writeFile('src/content/scenes.generated.ts', `// Generated by npm run assets:generate. Edit scripts/scenes/<id>.mjs.\nexport const sceneAssets = ${JSON.stringify(generated, null, 2)} as const\nexport const sceneAssetVersion = '${version}'\nexport const scenePackFiles = ${JSON.stringify(packs, null, 2)} as const\n`)
console.log(`Generated ${artworks.length} aligned SVG scene packs`)
